env: "local"

server:
  host: "localhost"
  port: ":8080"

worker:
  processed_time_out: 1s 

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "1106"
  dbname: "pet_project"
  sslmode: "disable"

redis:
  address: "localhost:6379"

jwt:
  token: "s1234tron1234g"
